title: Phil's Space
description: A space for things

url: "https://philcodex.github.io"
baseurl: "/phil-space"

remote_theme: daattali/beautiful-jekyll@6.0.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme